### ISSUE TITLE
Komma, Punt.

### ISSUE THREAD

**Issue by FutureCow** [tvwerkhoven/SBFspot2influxdb#1]
Top, een script waar ik al een tijdje naar op zoek was! 
Ik gebruik je CSV bestanden ook ergens anders voor en ik heb de komma ipv een punt voor de decimale cijfers. Die accepteert influxdb niet. Is er een manier om dit makkelijk op te lossen?

Volgens maar gaat er ook niets iets anders fout bij het parsen van de CSV bestanden:

{"error":"unable to parse 'energyv2 sma=15734\t2840400000 1551009606': invalid number\nunable to parse 'systemv2 sma=43,470 1551009606': invalid field format"}

bij systemv2 is het de comma, bij energyv2 wordt een verkeerd field uitgelezen?
(bestanden kun je hernoemen naar CSV)
[FutureCow-20190224.txt](https://github.com/tvwerkhoven/SBFspot2influxdb/files/2897860/FutureCow-20190224.txt)
[FutureCow-Spot-20190224.txt](https://github.com/tvwerkhoven/SBFspot2influxdb/files/2897861/FutureCow-Spot-20190224.txt)

**Comment by tvwerkhoven** [comment]
Glad to hear it's useful! I haven't tested with commas, so it makes sense something doesn't work. Regarding your errors:

1. Lua trips over the comma and converts this to a tab, hence you get two values in your query
2. The comma is not converted and influxdb doesn't like this.

I've added a fix which should resolve your issue.

**Comment by FutureCow** [comment]
Thank you for the quick reply, tested the new script, I get some values inside the DB!
Only the systemv2 is the temperature of the converter(41 degrees) and the energyv2 is another value i can't place: 56652642000, 15 minutes later: 56653844400

After reading the script properly, I see energyv2 is the total energy in joule, so this is correct! What is the easiest way of getting old data (from the last years) inside influxdb?

**Comment by tvwerkhoven** [comment]
The energyv2 values are energy generated in Joule. If you prefer kWh, you can remove the multiplication with 3600*1000 in the script.

I’m using Joule for all sensors so I can combine the data more easily (e.g. gas/heat).

**Comment by tvwerkhoven** [comment]
> After reading the script properly, I see energyv2 is the total energy in joule, so this is correct! What is the easiest way of getting old data (from the last years) inside influxdb?

I'm afraid that's not supported by this script, but you could loop over your CSV files and adapt this script to insert each line.
